name: Build and deploy Python app to Azure Web App - PricePred

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests
      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     pytest

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ./
            !./venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: List downloaded files
        run: ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DA1B6333A8D40ED8E40714F9530567E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_27C733EF5D1F4CCAA6BD8BF7E2C3CB9D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_78BF2E0CEF13498AB202AEE000EFB143 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PricePred'
          slot-name: 'Production'
          package: '.'  # Adjust this if your app is in a subfolder
